export const AppImages = {
  usFlag: require('./us-flag.png'),
  iconDownWhite: require('./icon-down-white.png'),
  eyeSlash: require('./eye-slash.png'),
  iconTabHome: require('./icon-tab-home.png'),
  iconTabHomeInactive: require('./icon-tab-home-inactive.png'),
  iconTabProfile: require('./icon-tab-profile.png'),
  iconTabProfileInactive: require('./icon-tab-profile-inactive.png'),
  iconTabBooking: require('./icon-tab-booking.png'),
  iconTabBookingInactive: require('./icon-tab-booking-inactive.png'),
  back: require('./back.png'),
  pencil: require('./pencil.png'),
  avatar: require('./avatar.png'),
  edit: require('./edit.png'),
  logout: require('./logout.png'),
};
